/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PPI.Vista;

import PPI.Modelos.ModeloProducto;
import PPI.Vistas.Interfaces.InterfazCatalogo;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Mauricio Caro
 */
public class VistaGenericaCatalogo extends javax.swing.JPanel {

    List<ModeloProducto> listaModeloProductos;
    VistaCatalogo vista;
    InterfazCatalogo listenerControlador;

    private int IdProductoSeleccionado;
    
    /**
     * Creates new form PanelPrincipalLibro
     * @param texto
     */
    
     public VistaGenericaCatalogo(List<ModeloProducto> listaModeloProductos, VistaCatalogo context) {
        this.listaModeloProductos = listaModeloProductos;
        vista = context;
    }
     
       public VistaGenericaCatalogo(String texto, String imagen, int idProducto, InterfazCatalogo listener) {
        initComponents();
        listenerControlador = listener;
        setTituloLibro(texto);
        setImagenLibro(imagen);
        IdProductoSeleccionado = idProducto;
    }

    public void crearProductos(InterfazCatalogo listener) {        
        for (int i = 0; i < listaModeloProductos.size(); i++) {
            VistaGenericaCatalogo producto = new VistaGenericaCatalogo(listaModeloProductos.get(i).getNombreProducto(), listaModeloProductos.get(i).getImagen(), listaModeloProductos.get(i).getIdProducto(), listener);
            vista.getPanelScroll().add(producto);
        }
        vista.getPanelScroll().updateUI();
    }
  
    private void setTituloLibro(String texto) {
        lblTituloPrincipal.setText(texto);
    }

    private void setImagenLibro(String imagen) {
        ImageIcon icon = new ImageIcon(System.getProperty("user.dir") + imagen);
        Icon icono = new ImageIcon(icon.getImage().getScaledInstance(100, 100, Image.SCALE_DEFAULT));
        lblImagenPrincipal.setText(null);
        lblImagenPrincipal.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblImagenPrincipal = new javax.swing.JLabel();
        lblTituloPrincipal = new javax.swing.JLabel();

        setBackground(new java.awt.Color(215, 204, 200));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setForeground(new java.awt.Color(215, 204, 200));

        lblImagenPrincipal.setText("Imagen");

        lblTituloPrincipal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTituloPrincipal.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTituloPrincipal.setText("titulo del libro");
        lblTituloPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTituloPrincipal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTituloPrincipalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblImagenPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblImagenPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblTituloPrincipalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTituloPrincipalMouseClicked
        listenerControlador.productoClicked(IdProductoSeleccionado);
    }//GEN-LAST:event_lblTituloPrincipalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblImagenPrincipal;
    private javax.swing.JLabel lblTituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
