/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PPI.Vista;

import PPI.Modelos.ModeloReserva;
import PPI.Vistas.Interfaces.InterfazMisReservas;
import java.awt.GridBagConstraints;
import java.awt.Image;
import java.util.List;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author Personal
 */
public class VistaGenericaProductos extends javax.swing.JPanel {


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblModificarMIsPublicaciones = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        lblImagenMisPulicaciones = new javax.swing.JLabel();
        lblTituloMisPublicaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblDescripcionMisPublicaciones = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(197, 225, 165));
        setForeground(new java.awt.Color(197, 225, 165));

        lblModificarMIsPublicaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit24.png"))); // NOI18N
        lblModificarMIsPublicaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblModificarMIsPublicacionesMouseClicked(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/delete24.png"))); // NOI18N
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        lblImagenMisPulicaciones.setText("Imagen");

        lblTituloMisPublicaciones.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTituloMisPublicaciones.setForeground(new java.awt.Color(0, 0, 0));
        lblTituloMisPublicaciones.setText("Titulo de libro");

        lblDescripcionMisPublicaciones.setEditable(false);
        lblDescripcionMisPublicaciones.setBackground(new java.awt.Color(197, 225, 165));
        lblDescripcionMisPublicaciones.setColumns(20);
        lblDescripcionMisPublicaciones.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDescripcionMisPublicaciones.setRows(5);
        jScrollPane1.setViewportView(lblDescripcionMisPublicaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(lblImagenMisPulicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblModificarMIsPublicaciones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloMisPublicaciones)
                        .addContainerGap(223, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloMisPublicaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblModificarMIsPublicaciones, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lblImagenMisPulicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblModificarMIsPublicacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblModificarMIsPublicacionesMouseClicked
    }//GEN-LAST:event_lblModificarMIsPublicacionesMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
    }//GEN-LAST:event_btnEliminarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea lblDescripcionMisPublicaciones;
    private javax.swing.JLabel lblImagenMisPulicaciones;
    private javax.swing.JLabel lblModificarMIsPublicaciones;
    private javax.swing.JLabel lblTituloMisPublicaciones;
    // End of variables declaration//GEN-END:variables
}
